#!/bin/sh -efu
if command -v ninja >/dev/null 2>&1; then
	use_ninja=-GNinja
fi
if test -n "${VERSION:-}"; then
	build_type=Release
fi

cmake -S . -B build ${use_ninja:-} \
	-DCMAKE_BUILD_TYPE="${build_type:-RelWithDebInfo}" \
	--install-prefix /usr
cmake --build build
