#!/bin/sh -efux
if command -v ninja >/dev/null 2>&1; then
	use_ninja=-GNinja
fi
build_type=${VERSION:+Release}

cmake -S . -B build ${use_ninja:-} \
	-DCMAKE_BUILD_TYPE="${build_type:-RelWithDebInfo}" \
	-DCMAKE_INSTALL_PREFIX="/usr"
cmake --build build
