name: Build AppImage

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-appimage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache Qt
        id:   cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run:  cmake -S . -B build
          --install-prefix /usr
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run:  cmake --build build
      - name: Install
        run:  DESTDIR=appdir cmake --install build

      - name: Package
        id:   pack-appimage
        run: |
          curl -JLso linuxdeployqt 'https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage'
          chmod a+x linuxdeployqt
          ./linuxdeployqt appdir/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so
          printf '::set-output name=appimage::%s' *.AppImage
        env:
          VERSION: latest
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.pack-appimage.outputs.appimage }}
          path: ${{ steps.pack-appimage.outputs.appimage }}
