name: AppImage Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'

jobs:
  build:
    name: Linux x86_64 (Continuous)
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - id:   cache
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}

      - name: Install dependencies
        run:  sudo apt-get install -y ninja-build

      - name: Build
        run:  etc/script/build

      - name: Package
        id:   package
        run:  etc/script/package

      - uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: DragDrop-*.AppImage*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Inspect downloaded artifacts
        run:  ls -lFR

      - name: Delete existing continuous tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: continuous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Continuous Build
          tag: continuous
          commit: ${{ github.sha }}
          artifacts: AppImage/DragDrop-*.AppImage*
          prerelease: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
