name: AppImage Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'

jobs:
  build:
    name: Linux x86_64 (Continuous)
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true

      - name: Install dependencies
        run:  sudo apt-get install -y ninja-build

      - name: Build
        run:  etc/script/build

      - name: Package
        id:   package
        run:  etc/script/package

      - uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: DragDrop-*.AppImage*
