name: AppImage Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'

jobs:
  appimage-build:
    name: Linux x86_64 (Continous)
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - id:   cache
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}

      - name: Install Dependencies
        run:  sudo apt-get install -y ninja-build

      - name: Build
        run:  etc/script/build

      - name: Package
        id:   package
        run: |
          etc/script/package
          printf '::set-output name=appimage::%s' DragDrop-*.AppImage

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.appimage }}
          path: ${{ steps.package.outputs.appimage }}
