name: AppImage Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'

jobs:
  build:
    name: Linux x86_64 (Continuous)
    runs-on: ubuntu-latest
    container: debian:oldstable-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential cmake qtbase5-dev ninja-build \
            ca-certificates curl file

      - name: Build
        run:  etc/ci/build

      - name: Package
        id:   package
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
        run:  etc/ci/package

      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: DragDrop-*.AppImage*
