name: AppImage Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'

jobs:
  build:
    name: Linux x86_64 (Continuous)
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential qtbase5-dev python3-pip p7zip-full unzip curl
          curl -sLOC- 'http://http.us.debian.org/debian/pool/main/x/xcb-util/libxcb-util1_0.4.0-1+b1_amd64.deb'
          dpkg -i libxcb-util1*.deb

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          install-deps: false
          cache: true
          setup-python: false

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Build
        run:  etc/ci/build

      - name: Package
        id:   package
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
        run:  etc/ci/package

      - uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: DragDrop-*.AppImage*
