name: AppImage Continuous

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.el'
      - '**.md'
      - '**.scm'
      - '.editorconfig'
      - '.gitignore'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    name: Linux x86_64 (Continuous)
    runs-on: ubuntu-latest
    container: debian:oldstable-slim

    steps:
      - uses: actions/checkout@v7

      - name: Install Dependencies
        run:  |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential cmake qt6-base-dev ninja-build \
            ca-certificates wget file

      - name: Install LinuxDeploy
        id:   linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: appimage qt

      - name: Set Up Environment
        run:  |
          exec >> ${GITHUB_ENV}
          echo REPO_ID=${GITHUB_REPOSITORY} | tr / \|
          case ${GITHUB_REF} in
            refs/tags/v*)
              echo VERSION=${GITHUB_REF##*/v}
              echo REPO_CH=latest
              ;;
            *)
              echo REPO_CH=continuous
              ;;
          esac
          printf 'ARCH=%s\n' $(uname -m)

      - name: Configure
        run:  >
          cmake -B build -G Ninja
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_INSTALL_LIBEXECDIR=bin
          -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run:  cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Install
        env:
          DESTDIR: appdir
        run:  cmake --install build --config ${{env.BUILD_TYPE}}

      - name: Package
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
          DISABLE_COPYRIGHT_FILES_DEPLOYMENT: 1
          UPDATE_INFORMATION: gh-releases-zsync|${{env.REPO_ID}}|${{env.REPO_CH}}|DragDrop-*${{env.ARCH}}.AppImage.zsync
        run:  >
          ${{steps.linuxdeploy.outputs.linuxdeploy}}
          --appdir appdir --plugin qt --output appimage

      - uses: actions/upload-artifact@v7
        with:
          name: AppImage
          path: DragDrop-*.AppImage*
