name: AppImage Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Linux x86_64 (Release)
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true

      - name: Install dependencies
        run:  sudo apt-get install -y ninja-build

      - name: Determine version
        run:  printf 'VERSION=%s\n' "${GITHUB_REF##*/v}" >> "${GITHUB_ENV}"

      - name: Build
        run:  etc/script/build

      - name: Package
        id:   package
        run:  etc/script/package

      - uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: DragDrop-*.AppImage*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Inspect downloaded artifacts
        run:  ls -lFR

      - name: Determine version
        run:  printf 'VERSION=%s\n'
          $(echo AppImage/DragDrop-*.AppImage | cut -f2 -d-) >> "${GITHUB_ENV}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: DragDrop ${{ env.VERSION }}
          artifacts: AppImage/DragDrop-*.AppImage*
          token: ${{ secrets.GITHUB_TOKEN }}
