name: AppImage Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Linux x86_64 (Release)
    runs-on: ubuntu-latest
    container: debian:oldstable-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential cmake qtbase5-dev ninja-build \
            ca-certificates curl file

      - name: Determine version
        run:  printf 'VERSION=%s\n' "${GITHUB_REF##*/v}" >> "${GITHUB_ENV}"

      - name: Build
        run:  etc/ci/build

      - name: Package
        id:   package
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
        run:  etc/ci/package

      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: DragDrop-*.AppImage*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Determine version
        run:  echo AppImage/*.AppImage |
          awk -F- '{print "VERSION=" $2}' >> "${GITHUB_ENV}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: DragDrop ${{ env.VERSION }}
          artifacts: AppImage/DragDrop-*.AppImage*
          token: ${{ secrets.GITHUB_TOKEN }}
